
server:
  port: 7071
  tomcat:
    max-connections: 2000 # Maximum connections
    accept-count: 200     # Maximum waiting number
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: always
    include-exception: true
    include-binding-errors: always

spring:
  boot:
    admin:
      client:
        # Cloud Native Spring Admin Server is running
        url: http://localhost:9090
  threads:
    virtual:
      enabled: true
  application:
    name: limiter-processor
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      observation-enabled: true
  cache:
    type: redis
    redis:
      cache-null-values: true
      use-key-prefix: true
      key-prefix: ECOMM-LIMITER-MS
      time-to-live: 5000
  data:
    redis:
      cluster:
        nodes: 127.0.0.1:6391, 127.0.0.1:6392, 127.0.0.1:6393
      connectTimeout: 5000
      timeout: 1000

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    git:
      mode: full
  tracing:
    enabled: true
    sampling:
      probability: 1.0

springdoc:
  show-actuator: false
  show-login-endpoint: false
  api-docs:
    path: /api
  swagger-ui:
    path: /
    operationsSorter: method
    disable-swagger-default-url: true

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5p) [${spring.application.name}] [%clr(%15.15t){faint}] [%clr(%32X{traceId}-%16X{spanId}){blue}] %clr(%40.40logger{5.10}:%-4L){cyan} : %m %n'
  level:
    io.oigres.ecomm.service.limiter: INFO

ecomm:
  termsOfService: https://ecomm.oigres.io/terms/
  license: https://ecomm.oigres.io/license/
  service:
    limiter:
      name: EComm
      version: ${project.version}
      rate-limit: 15
      topics:
        blacklisted-users: blacklisted-users-topic
    tracing:
      url: http://localhost:4318/v1/traces

