name: CI
on:
  push:
    branches: [ "**" ]
    
jobs:
  ci:
    name: ''
    uses: sjexpos/ecomm-cicd-actions/.github/workflows/app-ci.yaml@main
    secrets: inherit
    with:
      sonar_project_key: limiter-service
      sonar_project_name: Limiter Service
      docker_images: "['sjexposecomm/limiter-kafka-mps;./kafka-mps;./kafka-mps/Dockerfile', 'sjexposecomm/limiter-processor;./processor;./processor/Dockerfile']"
      files_as_artifacts: "['./model/target/limiter-service-model','./cache-lib/target/cache-lib']"

